#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

APP_BASE_NAME=$(basename "$0")
APP_HOME=$(dirname "$0")
APP_HOME=$(cd "$APP_HOME" > /dev/null && pwd)

DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

if [ -z "$JAVA_HOME" ]; then
    JAVA_CMD="java"
else
    JAVA_CMD="$JAVA_HOME/bin/java"
fi

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ ! -f "$CLASSPATH" ]; then
    echo "Gradle wrapper JAR not found. Downloading distribution..." 1>&2
    PROPERTIES_FILE="$APP_HOME/gradle/wrapper/gradle-wrapper.properties"
    if [ ! -f "$PROPERTIES_FILE" ]; then
        echo "Missing $PROPERTIES_FILE" 1>&2
        exit 1
    fi

    DISTRIBUTION_URL=$(grep '^distributionUrl=' "$PROPERTIES_FILE" | cut -d'=' -f2- | sed 's/\\:/:/g')
    if [ -z "$DISTRIBUTION_URL" ]; then
        echo "Unable to determine Gradle distribution URL." 1>&2
        exit 1
    fi

    TMP_DIR=$(mktemp -d)
    DISTRIBUTION_ZIP="$TMP_DIR/gradle-distribution.zip"

    if ! command -v curl >/dev/null 2>&1; then
        echo "curl is required to download the Gradle wrapper." 1>&2
        exit 1
    fi

    if ! command -v unzip >/dev/null 2>&1; then
        echo "unzip is required to extract the Gradle wrapper." 1>&2
        exit 1
    fi

    echo "Downloading $DISTRIBUTION_URL" 1>&2
    if ! curl -fsSL "$DISTRIBUTION_URL" -o "$DISTRIBUTION_ZIP"; then
        echo "Failed to download Gradle distribution." 1>&2
        rm -rf "$TMP_DIR"
        exit 1
    fi

    if ! unzip -j "$DISTRIBUTION_ZIP" 'gradle-*/lib/gradle-wrapper-*.jar' -d "$TMP_DIR" >/dev/null; then
        echo "Failed to extract Gradle wrapper JAR." 1>&2
        rm -rf "$TMP_DIR"
        exit 1
    fi

    WRAPPER_JAR=$(ls "$TMP_DIR"/gradle-wrapper-*.jar 2>/dev/null | head -n 1)
    if [ -z "$WRAPPER_JAR" ]; then
        echo "Gradle wrapper JAR not found in distribution." 1>&2
        rm -rf "$TMP_DIR"
        exit 1
    fi

    mkdir -p "$APP_HOME/gradle/wrapper"
    mv "$WRAPPER_JAR" "$CLASSPATH"
    rm -rf "$TMP_DIR"
fi

exec "$JAVA_CMD" $DEFAULT_JVM_OPTS -cp "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
